"""
Django settings for DjangoBlog project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/zh-hans/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/zh-hans/3.0/ref/settings/
"""
import sys
import os


def env_to_bool(env, default):
    str_val = os.environ.get(env)
    return default if str_val is None else str_val == 'True'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/zh-hans/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'n9ceqv38)#&mwuat@(mjb_p%em$e8$qyr#fw9ot!=ba6lijx-6'
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env_to_bool('DJANGO_DEBUG', True)
# DEBUG = False
DEBUG = True

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*', ]
# Application definition


SITE_ROOT = os.path.dirname(os.path.abspath(__file__))
SITE_ROOT = os.path.abspath(os.path.join(SITE_ROOT, '../'))

INSTALLED_APPS = [
    'simpleui',
    # 'django.contrib.admin',
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'ckeditor',
    'ckeditor_uploader',
    'mdeditor',
    'haystack',
    'django_extensions',
    # 'debug_toolbar',
    'blog',
    'accounts',
    'comments',
    'oauth',
    'servermanager',
    'owntracks',
    'compressor',
    'base',
    'home',
    'about',
    'service',
    'product',
    'case',
    'mobile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'blog.middleware.OnlineMiddleware'
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.seo_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'

# Database
# https://docs.djangoproject.com/zh-hans/3.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DJANGO_MYSQL_DATABASE') or 'qdqtrj_website',
        'USER': os.environ.get('DJANGO_MYSQL_USER') or 'root',
        'PASSWORD': os.environ.get('DJANGO_MYSQL_PASSWORD') or 'Ybkk1027',
        # 'HOST': os.environ.get('DJANGO_MYSQL_HOST') or '127.0.0.1',
        'HOST': os.environ.get('DJANGO_MYSQL_HOST') or '49.232.53.220',
        'PORT': int(os.environ.get('DJANGO_MYSQL_PORT') or 3306),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'qdqtrj_website',
    #     'USER': 'yinbin',
    #     'PASSWORD': 'Ybkk1027',
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432',
    # }
}

# Password validation
# https://docs.djangoproject.com/zh-hans/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/zh-hans/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_L10N = False

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/zh-hans/3.0/howto/static-files/


HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'website.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}
# Automatically update searching index
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# Allow user login with username and password
AUTHENTICATION_BACKENDS = ['accounts.user_login_backend.EmailOrUsernameModelBackend']

STATIC_ROOT = os.path.join(SITE_ROOT, 'collectedstatic')

STATIC_URL = '/static/'
STATICFILES = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'uploads'),
]

AUTH_USER_MODEL = 'accounts.BlogUser'
LOGIN_URL = '/login/'

TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATE_TIME_FORMAT = '%Y-%m-%d'

# bootstrap color styles
BOOTSTRAP_COLOR_TYPES = [
    'default', 'primary', 'success', 'info', 'warning', 'danger'
]

# paginate
PAGINATE_BY = 10
# http cache timeout
CACHE_CONTROL_MAX_AGE = 2592000
# cache setting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': os.environ.get('DJANGO_MEMCACHED_LOCATION') or '127.0.0.1:11211',
        'KEY_PREFIX': 'django_test' if TESTING else 'djangoblog',
        'TIMEOUT': 60 * 60 * 10
    } if env_to_bool('DJANGO_MEMCACHED_ENABLE', True) else {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 10800,
        'LOCATION': 'unique-snowflake',
    }
}

SITE_ID = 1
BAIDU_NOTIFY_URL = os.environ.get('DJANGO_BAIDU_NOTIFY_URL') \
                   or 'http://data.zz.baidu.com/urls?site=https://www.lylinux.net&token=1uAOGrMsUm5syDGn'

# Email:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = env_to_bool('DJANGO_EMAIL_TLS', False)
EMAIL_USE_SSL = env_to_bool('DJANGO_EMAIL_SSL', False)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST') or 'smtp.163.com'
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT') or 25)
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_USER') or 'ybkk1027@163.com'
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_PASSWORD') or 'Ybkk1027'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
# Setting debug=false did NOT handle except email notifications
ADMINS = [('admin', os.environ.get('DJANGO_ADMIN_EMAIL') or 'admin@admin.com')]
# WX ADMIN password(Two times md5)
WXADMIN = os.environ.get('DJANGO_WXADMIN_PASSWORD') or '995F03AC401D6CABABAEF756FC4D43C7'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': 'INFO',
        'handlers': ['console', 'log_file'],
    },
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d %(module)s] %(message)s',
        }
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'log_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'website.log',
            'maxBytes': 16777216,  # 16 MB
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'djangoblog': {
            'handlers': ['log_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other
    'compressor.finders.CompressorFinder',
)
# COMPRESS_ENABLED = True
COMPRESS_ENABLED = False
# COMPRESS_OFFLINE = True


COMPRESS_CSS_FILTERS = [
    # creates absolute urls from relative ones
    'compressor.filters.css_default.CssAbsoluteFilter',
    # css minimizer
    'compressor.filters.cssmin.CSSMinFilter'
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter'
]

MEDIA_ROOT = os.path.join(SITE_ROOT, 'uploads')
MEDIA_URL = '/media/'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ckeditor 编辑器
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_MEDIA_PREFIX = "static/ckeditor/"
CKEDITOR_UPLOAD_PATH = "ckupload/"
CKEDITOR_CONFIGS = {
    'default': {
        'height': 500,
        'width': 1400,
    },
    'full': {
        'toolbar': 'full',
        'height': 700,
        'width': 1400,
    },
    'mini': {
        'toolbar': 'Basic',
        'height': 200,
        'width': 600,
    },
}

# Markdown 编辑器
# MDEDITOR_CONFIGS = {
#     'default': {
#         'width': '100% ',  # Custom edit box width
#         'heigth': 500,  # Custom edit box height
#         'toolbar': ["undo", "redo", "|",
#                     "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
#                     "h1", "h2", "h3", "h5", "h6", "|",
#                     "list-ul", "list-ol", "hr", "|",
#                     "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table",
#                     "datetime"
#                     "emoji",
#                     "html-entities", "pagebreak", "goto-line", "|",
#                     "help", "info",
#                     "||", "preview", "watch", "fullscreen"],  # custom edit box toolbar
#         'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # image upload format type
#         'image_floder': 'editor',  # image save the folder name
#         'theme': 'default',  # edit box theme, dark / default
#         'preview_theme': 'default',  # Preview area theme, dark / default
#         'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
#         'toolbar_autofixed': True,  # Whether the toolbar capitals
#         'search_replace': True,  # Whether to open the search for replacement
#         'emoji': True,  # whether to open the expression function
#         'tex': False,  # whether to open the tex chart function
#         'flow_chart': True,  # whether to open the flow chart function
#         'sequence': True,  # Whether to open the sequence diagram function
#         'mermaid': True,  # mermaid
#         'vega': True,
#     }
# }

# simpleui 自定义菜单
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_CONFIG2 = {
    'system_keep': True,
    'menu_display': [
        '前途软件官网',
        '基本管理',
        '权限管理',
        '博客管理',
        '网站管理',
    ],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': False,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'name': '基本管理',
            'icon': 'fas fa-file',
            'models': [
                {'name': '站点管理', 'icon': 'fa fa-file', 'url': '/admin/sites/site/'},
                {'name': '快速执行命令', 'icon': 'fa fa-file', 'url': '/admin/servermanager/commands/'},
                {'name': '邮件发送日志', 'icon': 'fa fa-file', 'url': '/admin/servermanager/emailsendlog/'},
                {'name': '后台操作日志', 'icon': 'fa fa-file', 'url': '/admin/admin/logentry/'},
            ]
        },
        {
            'name': '权限管理',
            'icon': 'fa fa-file',
            'models': [
                {'name': '博客账号', 'icon': 'fa fa-file', 'url': '/admin/accounts/bloguser/'},
                {'name': '用户管理', 'icon': 'fa fa-file', 'url': '/admin/oauth/oauthuser/'},
                {'name': '权限配置', 'icon': 'fa fa-file', 'url': '/admin/oauth/oauthconfig/'},
                {'name': '邮件发送', 'icon': 'fa fa-file', 'url': '/admin/servermanager/emailsendlog/'},
            ]
        },
        {
            'name': '博客管理',
            'icon': 'fa fa-file',
            'models': [
                {'name': '侧边栏', 'icon': 'fa fa-file', 'url': '/admin/blog/sidebar/'},
                {'name': '分类', 'icon': 'fa fa-file', 'url': '/admin/blog/category/'},
                {'name': '友情链接', 'icon': 'fa fa-file', 'url': '/admin/blog/links/'},
                {'name': '文章', 'icon': 'fa fa-file', 'url': '/admin/blog/article/'},
                {'name': '标签', 'icon': 'fa fa-file', 'url': '/admin/blog/tag/'},
                {'name': '博客评论', 'icon': 'fa fa-file', 'url': '/admin/comments/comment/'},
                {'name': '访问位置', 'icon': 'fa fa-file', 'url': '/admin/owntracks/owntracklog/'},
            ]
        },
        {
            'name': '网站管理',
            'icon': 'fa fa-file',
            'models': [
                {'name': 'SEO', 'icon': 'fa fa-file', 'url': '/admin/base/websettings/'},
                {'name': '主页', 'icon': 'fa fa-file', 'url': '/admin/home/home/'},
                {'name': '服务', 'icon': 'fa fa-file', 'url': '/admin/service/service/'},
                {'name': '产品', 'icon': 'fa fa-file', 'url': '/admin/service/product/'},
                {'name': '案例-分类', 'icon': 'fa fa-file', 'url': '/admin/case/category/'},
                {'name': '案例', 'icon': 'fa fa-file', 'url': '/admin/case/case/'},
                {'name': '留言', 'icon': 'fa fa-file', 'url': '//admin/base/message/'},
                {'name': '关于', 'icon': 'fa fa-file', 'url': '/admin/about/about/'},
            ]
        },

    ]
}
